### ISSUE TITLE
Delete host confirmation

### ISSUE THREAD

**Issue by htbase** [diego-treitos/ansible-inventory#7]
Hi there

When we try to delete a host, it asks for confirmation.
Ideally, we are trying to delete it using the --batch option, so we can process it on the background

Even when using the --batch, it still asks for confirmation [y/n]. Is there a way to pass that confirmation through the batch as well?

**Comment by diego-treitos** [comment]
For the record, I thought that it might be a good idea to also have the confirmation via batch as it is very easy to bypass using `echo y | ansible-inv --batch 'del host my_host'` and it might help to avoid some unwanted deletions.
